networks:
  eco-network:

services:
  ecostep.api:
    image: ${DOCKER_REGISTRY-}ecostepapi
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    build:
      context: .
      dockerfile: EcoStep.Api/Dockerfile
    networks:
      - eco-network

  postgres-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: VanGoDb
    ports:
      - "5432:5432"
    networks:
      - eco-network
